### ISSUE TITLE
Time Series Data

### ISSUE THREAD

**Issue by Logner** [StevenTraboulay/StockApp.github.io#6]
Pull time series data from 'yesterday'.

expirement with 15min vs 30min time series api calls.

search for time series data from 9:30-16:00

store data to var stockTimeSeries = {};

**Comment by asgharbhutta** [comment]
Pull time series data from 'yesterday'. - Complete

expirement with 15min vs 30min time series api calls. - Complete - 15min calls are used

search for time series data from 9:30-16:00 - Complete - 9:45-16 are used

store data to var stockTimeSeries = {}; - Complete data is stored in variable listOfCloseValues and not stockTimeSeries @Logner

**Comment by asgharbhutta** [comment]
Closed @Logner new variable for visualization if required is stored in listOfCloseValues
